#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vshapeup.com
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VShapeUp")]
	public partial class VShapeUpDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChallenger(Challenger instance);
    partial void UpdateChallenger(Challenger instance);
    partial void DeleteChallenger(Challenger instance);
    partial void InsertBodyComposition(BodyComposition instance);
    partial void UpdateBodyComposition(BodyComposition instance);
    partial void DeleteBodyComposition(BodyComposition instance);
    partial void InsertIndexMaster(IndexMaster instance);
    partial void UpdateIndexMaster(IndexMaster instance);
    partial void DeleteIndexMaster(IndexMaster instance);
    partial void InsertOPPData(OPPData instance);
    partial void UpdateOPPData(OPPData instance);
    partial void DeleteOPPData(OPPData instance);
    partial void InsertPage(Page instance);
    partial void UpdatePage(Page instance);
    partial void DeletePage(Page instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public VShapeUpDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VShapeUpConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VShapeUpDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VShapeUpDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VShapeUpDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VShapeUpDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Challenger> Challengers
		{
			get
			{
				return this.GetTable<Challenger>();
			}
		}
		
		public System.Data.Linq.Table<BodyComposition> BodyCompositions
		{
			get
			{
				return this.GetTable<BodyComposition>();
			}
		}
		
		public System.Data.Linq.Table<IndexMaster> IndexMasters
		{
			get
			{
				return this.GetTable<IndexMaster>();
			}
		}
		
		public System.Data.Linq.Table<OPPData> OPPDatas
		{
			get
			{
				return this.GetTable<OPPData>();
			}
		}
		
		public System.Data.Linq.Table<V_ChallengeResult> V_ChallengeResults
		{
			get
			{
				return this.GetTable<V_ChallengeResult>();
			}
		}
		
		public System.Data.Linq.Table<V_RegisterChallengeResult_Report> V_RegisterChallengeResult_Reports
		{
			get
			{
				return this.GetTable<V_RegisterChallengeResult_Report>();
			}
		}
		
		public System.Data.Linq.Table<V_ChallengeResult_Report> V_ChallengeResult_Reports
		{
			get
			{
				return this.GetTable<V_ChallengeResult_Report>();
			}
		}
		
		public System.Data.Linq.Table<Page> Pages
		{
			get
			{
				return this.GetTable<Page>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Challenger")]
	public partial class Challenger : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserNo;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _NickName;
		
		private string _Telephone;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<double> _Height;
		
		private string _Gender;
		
		private string _Invitor;
		
		private string _LineID;
		
		private System.Nullable<System.DateTime> _CreatedAt;
		
		private System.Nullable<System.DateTime> _ModifiedAt;
		
		private bool _IsChanllenge;
		
		private bool _IsComplete;
		
		private System.Nullable<byte> _OOP;
		
		private EntitySet<BodyComposition> _BodyCompositions;
		
		private EntitySet<Page> _Pages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNoChanging(string value);
    partial void OnUserNoChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnNickNameChanging(string value);
    partial void OnNickNameChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnHeightChanging(System.Nullable<double> value);
    partial void OnHeightChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnInvitorChanging(string value);
    partial void OnInvitorChanged();
    partial void OnLineIDChanging(string value);
    partial void OnLineIDChanged();
    partial void OnCreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedAtChanged();
    partial void OnModifiedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedAtChanged();
    partial void OnIsChanllengeChanging(bool value);
    partial void OnIsChanllengeChanged();
    partial void OnIsCompleteChanging(bool value);
    partial void OnIsCompleteChanged();
    partial void OnOOPChanging(System.Nullable<byte> value);
    partial void OnOOPChanged();
    #endregion
		
		public Challenger()
		{
			this._BodyCompositions = new EntitySet<BodyComposition>(new Action<BodyComposition>(this.attach_BodyCompositions), new Action<BodyComposition>(this.detach_BodyCompositions));
			this._Pages = new EntitySet<Page>(new Action<Page>(this.attach_Pages), new Action<Page>(this.detach_Pages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserNo
		{
			get
			{
				return this._UserNo;
			}
			set
			{
				if ((this._UserNo != value))
				{
					this.OnUserNoChanging(value);
					this.SendPropertyChanging();
					this._UserNo = value;
					this.SendPropertyChanged("UserNo");
					this.OnUserNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName", DbType="VarChar(50)")]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this.OnNickNameChanging(value);
					this.SendPropertyChanging();
					this._NickName = value;
					this.SendPropertyChanged("NickName");
					this.OnNickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Float")]
		public System.Nullable<double> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(1)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invitor", DbType="VarChar(50)")]
		public string Invitor
		{
			get
			{
				return this._Invitor;
			}
			set
			{
				if ((this._Invitor != value))
				{
					this.OnInvitorChanging(value);
					this.SendPropertyChanging();
					this._Invitor = value;
					this.SendPropertyChanged("Invitor");
					this.OnInvitorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineID", DbType="VarChar(50)")]
		public string LineID
		{
			get
			{
				return this._LineID;
			}
			set
			{
				if ((this._LineID != value))
				{
					this.OnLineIDChanging(value);
					this.SendPropertyChanging();
					this._LineID = value;
					this.SendPropertyChanged("LineID");
					this.OnLineIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedAt
		{
			get
			{
				return this._ModifiedAt;
			}
			set
			{
				if ((this._ModifiedAt != value))
				{
					this.OnModifiedAtChanging(value);
					this.SendPropertyChanging();
					this._ModifiedAt = value;
					this.SendPropertyChanged("ModifiedAt");
					this.OnModifiedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChanllenge", DbType="Bit NOT NULL")]
		public bool IsChanllenge
		{
			get
			{
				return this._IsChanllenge;
			}
			set
			{
				if ((this._IsChanllenge != value))
				{
					this.OnIsChanllengeChanging(value);
					this.SendPropertyChanging();
					this._IsChanllenge = value;
					this.SendPropertyChanged("IsChanllenge");
					this.OnIsChanllengeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsComplete", DbType="Bit NOT NULL")]
		public bool IsComplete
		{
			get
			{
				return this._IsComplete;
			}
			set
			{
				if ((this._IsComplete != value))
				{
					this.OnIsCompleteChanging(value);
					this.SendPropertyChanging();
					this._IsComplete = value;
					this.SendPropertyChanged("IsComplete");
					this.OnIsCompleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OOP", DbType="TinyInt")]
		public System.Nullable<byte> OOP
		{
			get
			{
				return this._OOP;
			}
			set
			{
				if ((this._OOP != value))
				{
					this.OnOOPChanging(value);
					this.SendPropertyChanging();
					this._OOP = value;
					this.SendPropertyChanged("OOP");
					this.OnOOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Challenger_BodyComposition", Storage="_BodyCompositions", ThisKey="UserNo", OtherKey="UserNo")]
		public EntitySet<BodyComposition> BodyCompositions
		{
			get
			{
				return this._BodyCompositions;
			}
			set
			{
				this._BodyCompositions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Challenger_Page", Storage="_Pages", ThisKey="UserNo", OtherKey="UserNo")]
		public EntitySet<Page> Pages
		{
			get
			{
				return this._Pages;
			}
			set
			{
				this._Pages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BodyCompositions(BodyComposition entity)
		{
			this.SendPropertyChanging();
			entity.Challenger = this;
		}
		
		private void detach_BodyCompositions(BodyComposition entity)
		{
			this.SendPropertyChanging();
			entity.Challenger = null;
		}
		
		private void attach_Pages(Page entity)
		{
			this.SendPropertyChanging();
			entity.Challenger = this;
		}
		
		private void detach_Pages(Page entity)
		{
			this.SendPropertyChanging();
			entity.Challenger = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BodyComposition")]
	public partial class BodyComposition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserNo;
		
		private System.DateTime _MeasureDate;
		
		private System.Nullable<double> _Weight;
		
		private System.Nullable<double> _Fat;
		
		private System.Nullable<double> _VisFat;
		
		private System.Nullable<double> _Muscle;
		
		private System.Nullable<int> _BodyAge;
		
		private System.Nullable<double> _BMR;
		
		private System.Nullable<double> _BMI;
		
		private EntityRef<Challenger> _Challenger;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNoChanging(string value);
    partial void OnUserNoChanged();
    partial void OnMeasureDateChanging(System.DateTime value);
    partial void OnMeasureDateChanged();
    partial void OnWeightChanging(System.Nullable<double> value);
    partial void OnWeightChanged();
    partial void OnFatChanging(System.Nullable<double> value);
    partial void OnFatChanged();
    partial void OnVisFatChanging(System.Nullable<double> value);
    partial void OnVisFatChanged();
    partial void OnMuscleChanging(System.Nullable<double> value);
    partial void OnMuscleChanged();
    partial void OnBodyAgeChanging(System.Nullable<int> value);
    partial void OnBodyAgeChanged();
    partial void OnBMRChanging(System.Nullable<double> value);
    partial void OnBMRChanged();
    partial void OnBMIChanging(System.Nullable<double> value);
    partial void OnBMIChanged();
    #endregion
		
		public BodyComposition()
		{
			this._Challenger = default(EntityRef<Challenger>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserNo
		{
			get
			{
				return this._UserNo;
			}
			set
			{
				if ((this._UserNo != value))
				{
					if (this._Challenger.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserNoChanging(value);
					this.SendPropertyChanging();
					this._UserNo = value;
					this.SendPropertyChanged("UserNo");
					this.OnUserNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime MeasureDate
		{
			get
			{
				return this._MeasureDate;
			}
			set
			{
				if ((this._MeasureDate != value))
				{
					this.OnMeasureDateChanging(value);
					this.SendPropertyChanging();
					this._MeasureDate = value;
					this.SendPropertyChanged("MeasureDate");
					this.OnMeasureDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float")]
		public System.Nullable<double> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat", DbType="Float")]
		public System.Nullable<double> Fat
		{
			get
			{
				return this._Fat;
			}
			set
			{
				if ((this._Fat != value))
				{
					this.OnFatChanging(value);
					this.SendPropertyChanging();
					this._Fat = value;
					this.SendPropertyChanged("Fat");
					this.OnFatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat", DbType="Float")]
		public System.Nullable<double> VisFat
		{
			get
			{
				return this._VisFat;
			}
			set
			{
				if ((this._VisFat != value))
				{
					this.OnVisFatChanging(value);
					this.SendPropertyChanging();
					this._VisFat = value;
					this.SendPropertyChanged("VisFat");
					this.OnVisFatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle", DbType="Float")]
		public System.Nullable<double> Muscle
		{
			get
			{
				return this._Muscle;
			}
			set
			{
				if ((this._Muscle != value))
				{
					this.OnMuscleChanging(value);
					this.SendPropertyChanging();
					this._Muscle = value;
					this.SendPropertyChanged("Muscle");
					this.OnMuscleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge", DbType="Int")]
		public System.Nullable<int> BodyAge
		{
			get
			{
				return this._BodyAge;
			}
			set
			{
				if ((this._BodyAge != value))
				{
					this.OnBodyAgeChanging(value);
					this.SendPropertyChanging();
					this._BodyAge = value;
					this.SendPropertyChanged("BodyAge");
					this.OnBodyAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR", DbType="Float")]
		public System.Nullable<double> BMR
		{
			get
			{
				return this._BMR;
			}
			set
			{
				if ((this._BMR != value))
				{
					this.OnBMRChanging(value);
					this.SendPropertyChanging();
					this._BMR = value;
					this.SendPropertyChanged("BMR");
					this.OnBMRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Float")]
		public System.Nullable<double> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this.OnBMIChanging(value);
					this.SendPropertyChanging();
					this._BMI = value;
					this.SendPropertyChanged("BMI");
					this.OnBMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Challenger_BodyComposition", Storage="_Challenger", ThisKey="UserNo", OtherKey="UserNo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Challenger Challenger
		{
			get
			{
				return this._Challenger.Entity;
			}
			set
			{
				Challenger previousValue = this._Challenger.Entity;
				if (((previousValue != value) 
							|| (this._Challenger.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Challenger.Entity = null;
						previousValue.BodyCompositions.Remove(this);
					}
					this._Challenger.Entity = value;
					if ((value != null))
					{
						value.BodyCompositions.Add(this);
						this._UserNo = value.UserNo;
					}
					else
					{
						this._UserNo = default(string);
					}
					this.SendPropertyChanged("Challenger");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IndexMaster")]
	public partial class IndexMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DocSeries;
		
		private string _Docyear;
		
		private string _Docmonth;
		
		private System.Nullable<int> _DocNo;
		
		private System.Nullable<byte> _DocLen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDocSeriesChanging(string value);
    partial void OnDocSeriesChanged();
    partial void OnDocyearChanging(string value);
    partial void OnDocyearChanged();
    partial void OnDocmonthChanging(string value);
    partial void OnDocmonthChanged();
    partial void OnDocNoChanging(System.Nullable<int> value);
    partial void OnDocNoChanged();
    partial void OnDocLenChanging(System.Nullable<byte> value);
    partial void OnDocLenChanged();
    #endregion
		
		public IndexMaster()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocSeries", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DocSeries
		{
			get
			{
				return this._DocSeries;
			}
			set
			{
				if ((this._DocSeries != value))
				{
					this.OnDocSeriesChanging(value);
					this.SendPropertyChanging();
					this._DocSeries = value;
					this.SendPropertyChanged("DocSeries");
					this.OnDocSeriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Docyear", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Docyear
		{
			get
			{
				return this._Docyear;
			}
			set
			{
				if ((this._Docyear != value))
				{
					this.OnDocyearChanging(value);
					this.SendPropertyChanging();
					this._Docyear = value;
					this.SendPropertyChanged("Docyear");
					this.OnDocyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Docmonth", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Docmonth
		{
			get
			{
				return this._Docmonth;
			}
			set
			{
				if ((this._Docmonth != value))
				{
					this.OnDocmonthChanging(value);
					this.SendPropertyChanging();
					this._Docmonth = value;
					this.SendPropertyChanged("Docmonth");
					this.OnDocmonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocNo", DbType="Int")]
		public System.Nullable<int> DocNo
		{
			get
			{
				return this._DocNo;
			}
			set
			{
				if ((this._DocNo != value))
				{
					this.OnDocNoChanging(value);
					this.SendPropertyChanging();
					this._DocNo = value;
					this.SendPropertyChanged("DocNo");
					this.OnDocNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocLen", DbType="TinyInt")]
		public System.Nullable<byte> DocLen
		{
			get
			{
				return this._DocLen;
			}
			set
			{
				if ((this._DocLen != value))
				{
					this.OnDocLenChanging(value);
					this.SendPropertyChanging();
					this._DocLen = value;
					this.SendPropertyChanged("DocLen");
					this.OnDocLenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OPPData")]
	public partial class OPPData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _ID;
		
		private byte _OPPNo;
		
		private System.DateTime _OPPDate;
		
		private string _RegisterPrefix;
		
		private bool _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(byte value);
    partial void OnIDChanged();
    partial void OnOPPNoChanging(byte value);
    partial void OnOPPNoChanged();
    partial void OnOPPDateChanging(System.DateTime value);
    partial void OnOPPDateChanged();
    partial void OnRegisterPrefixChanging(string value);
    partial void OnRegisterPrefixChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    #endregion
		
		public OPPData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPPNo", DbType="TinyInt NOT NULL")]
		public byte OPPNo
		{
			get
			{
				return this._OPPNo;
			}
			set
			{
				if ((this._OPPNo != value))
				{
					this.OnOPPNoChanging(value);
					this.SendPropertyChanging();
					this._OPPNo = value;
					this.SendPropertyChanged("OPPNo");
					this.OnOPPNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPPDate", DbType="DateTime NOT NULL")]
		public System.DateTime OPPDate
		{
			get
			{
				return this._OPPDate;
			}
			set
			{
				if ((this._OPPDate != value))
				{
					this.OnOPPDateChanging(value);
					this.SendPropertyChanging();
					this._OPPDate = value;
					this.SendPropertyChanged("OPPDate");
					this.OnOPPDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterPrefix", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string RegisterPrefix
		{
			get
			{
				return this._RegisterPrefix;
			}
			set
			{
				if ((this._RegisterPrefix != value))
				{
					this.OnRegisterPrefixChanging(value);
					this.SendPropertyChanging();
					this._RegisterPrefix = value;
					this.SendPropertyChanged("RegisterPrefix");
					this.OnRegisterPrefixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_ChallengeResult")]
	public partial class V_ChallengeResult
	{
		
		private string _UserNo;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _NickName;
		
		private string _Telephone;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<double> _Height;
		
		private string _Gender;
		
		private string _Invitor;
		
		private System.DateTime _MeasureDate;
		
		private System.Nullable<double> _Weight;
		
		private System.Nullable<double> _Fat;
		
		private System.Nullable<double> _VisFat;
		
		private System.Nullable<double> _Muscle;
		
		private System.Nullable<int> _BodyAge;
		
		private System.Nullable<double> _BMR;
		
		private System.Nullable<double> _BMI;
		
		private string _LineID;
		
		private System.Nullable<byte> _OOP;
		
		public V_ChallengeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UserNo
		{
			get
			{
				return this._UserNo;
			}
			set
			{
				if ((this._UserNo != value))
				{
					this._UserNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName", DbType="VarChar(50)")]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this._NickName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Float")]
		public System.Nullable<double> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this._Height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(1)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invitor", DbType="VarChar(50)")]
		public string Invitor
		{
			get
			{
				return this._Invitor;
			}
			set
			{
				if ((this._Invitor != value))
				{
					this._Invitor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate", DbType="DateTime NOT NULL")]
		public System.DateTime MeasureDate
		{
			get
			{
				return this._MeasureDate;
			}
			set
			{
				if ((this._MeasureDate != value))
				{
					this._MeasureDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float")]
		public System.Nullable<double> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat", DbType="Float")]
		public System.Nullable<double> Fat
		{
			get
			{
				return this._Fat;
			}
			set
			{
				if ((this._Fat != value))
				{
					this._Fat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat", DbType="Float")]
		public System.Nullable<double> VisFat
		{
			get
			{
				return this._VisFat;
			}
			set
			{
				if ((this._VisFat != value))
				{
					this._VisFat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle", DbType="Float")]
		public System.Nullable<double> Muscle
		{
			get
			{
				return this._Muscle;
			}
			set
			{
				if ((this._Muscle != value))
				{
					this._Muscle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge", DbType="Int")]
		public System.Nullable<int> BodyAge
		{
			get
			{
				return this._BodyAge;
			}
			set
			{
				if ((this._BodyAge != value))
				{
					this._BodyAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR", DbType="Float")]
		public System.Nullable<double> BMR
		{
			get
			{
				return this._BMR;
			}
			set
			{
				if ((this._BMR != value))
				{
					this._BMR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Float")]
		public System.Nullable<double> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this._BMI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineID", DbType="VarChar(50)")]
		public string LineID
		{
			get
			{
				return this._LineID;
			}
			set
			{
				if ((this._LineID != value))
				{
					this._LineID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OOP", DbType="TinyInt")]
		public System.Nullable<byte> OOP
		{
			get
			{
				return this._OOP;
			}
			set
			{
				if ((this._OOP != value))
				{
					this._OOP = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_RegisterChallengeResult_Report")]
	public partial class V_RegisterChallengeResult_Report
	{
		
		private string _UserNo;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _NickName;
		
		private string _Telephone;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<double> _Height;
		
		private string _Gender;
		
		private string _Invitor;
		
		private string _LineID;
		
		private System.Nullable<int> _Page;
		
		private System.Nullable<int> _Number1;
		
		private string _MeasureDate1;
		
		private System.Nullable<double> _Weight1;
		
		private System.Nullable<double> _Fat1;
		
		private System.Nullable<double> _VisFat1;
		
		private System.Nullable<double> _Muscle1;
		
		private System.Nullable<int> _BodyAge1;
		
		private System.Nullable<double> _BMR1;
		
		private System.Nullable<double> _BMI1;
		
		private System.Nullable<int> _Number2;
		
		private string _MeasureDate2;
		
		private System.Nullable<double> _Weight2;
		
		private System.Nullable<double> _Fat2;
		
		private System.Nullable<double> _VisFat2;
		
		private System.Nullable<double> _Muscle2;
		
		private System.Nullable<int> _BodyAge2;
		
		private System.Nullable<double> _BMR2;
		
		private System.Nullable<double> _BMI2;
		
		private System.Nullable<int> _Number3;
		
		private string _MeasureDate3;
		
		private System.Nullable<double> _Weight3;
		
		private System.Nullable<double> _Fat3;
		
		private System.Nullable<double> _VisFat3;
		
		private System.Nullable<double> _Muscle3;
		
		private System.Nullable<int> _BodyAge3;
		
		private System.Nullable<double> _BMR3;
		
		private System.Nullable<double> _BMI3;
		
		private System.Nullable<int> _Number4;
		
		private string _MeasureDate4;
		
		private System.Nullable<double> _Weight4;
		
		private System.Nullable<double> _Fat4;
		
		private System.Nullable<double> _VisFat4;
		
		private System.Nullable<double> _Muscle4;
		
		private System.Nullable<int> _BodyAge4;
		
		private System.Nullable<double> _BMR4;
		
		private System.Nullable<double> _BMI4;
		
		private System.Nullable<int> _Number5;
		
		private string _MeasureDate5;
		
		private System.Nullable<double> _Weight5;
		
		private System.Nullable<double> _Fat5;
		
		private System.Nullable<double> _VisFat5;
		
		private System.Nullable<double> _Muscle5;
		
		private System.Nullable<int> _BodyAge5;
		
		private System.Nullable<double> _BMR5;
		
		private System.Nullable<double> _BMI5;
		
		private System.Nullable<double> _Fat;
		
		private System.Nullable<double> _VisFat;
		
		private System.Nullable<double> _Muscle;
		
		private System.Nullable<int> _BodyAge;
		
		private System.Nullable<double> _BMR;
		
		private System.Nullable<double> _BMI;
		
		public V_RegisterChallengeResult_Report()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UserNo
		{
			get
			{
				return this._UserNo;
			}
			set
			{
				if ((this._UserNo != value))
				{
					this._UserNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName", DbType="VarChar(50)")]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this._NickName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Float")]
		public System.Nullable<double> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this._Height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(1)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invitor", DbType="VarChar(50)")]
		public string Invitor
		{
			get
			{
				return this._Invitor;
			}
			set
			{
				if ((this._Invitor != value))
				{
					this._Invitor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineID", DbType="VarChar(50)")]
		public string LineID
		{
			get
			{
				return this._LineID;
			}
			set
			{
				if ((this._LineID != value))
				{
					this._LineID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Page", DbType="Int")]
		public System.Nullable<int> Page
		{
			get
			{
				return this._Page;
			}
			set
			{
				if ((this._Page != value))
				{
					this._Page = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number1", DbType="Int")]
		public System.Nullable<int> Number1
		{
			get
			{
				return this._Number1;
			}
			set
			{
				if ((this._Number1 != value))
				{
					this._Number1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate1", DbType="VarChar(10)")]
		public string MeasureDate1
		{
			get
			{
				return this._MeasureDate1;
			}
			set
			{
				if ((this._MeasureDate1 != value))
				{
					this._MeasureDate1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight1", DbType="Float")]
		public System.Nullable<double> Weight1
		{
			get
			{
				return this._Weight1;
			}
			set
			{
				if ((this._Weight1 != value))
				{
					this._Weight1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat1", DbType="Float")]
		public System.Nullable<double> Fat1
		{
			get
			{
				return this._Fat1;
			}
			set
			{
				if ((this._Fat1 != value))
				{
					this._Fat1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat1", DbType="Float")]
		public System.Nullable<double> VisFat1
		{
			get
			{
				return this._VisFat1;
			}
			set
			{
				if ((this._VisFat1 != value))
				{
					this._VisFat1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle1", DbType="Float")]
		public System.Nullable<double> Muscle1
		{
			get
			{
				return this._Muscle1;
			}
			set
			{
				if ((this._Muscle1 != value))
				{
					this._Muscle1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge1", DbType="Int")]
		public System.Nullable<int> BodyAge1
		{
			get
			{
				return this._BodyAge1;
			}
			set
			{
				if ((this._BodyAge1 != value))
				{
					this._BodyAge1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR1", DbType="Float")]
		public System.Nullable<double> BMR1
		{
			get
			{
				return this._BMR1;
			}
			set
			{
				if ((this._BMR1 != value))
				{
					this._BMR1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI1", DbType="Float")]
		public System.Nullable<double> BMI1
		{
			get
			{
				return this._BMI1;
			}
			set
			{
				if ((this._BMI1 != value))
				{
					this._BMI1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number2", DbType="Int")]
		public System.Nullable<int> Number2
		{
			get
			{
				return this._Number2;
			}
			set
			{
				if ((this._Number2 != value))
				{
					this._Number2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate2", DbType="VarChar(10)")]
		public string MeasureDate2
		{
			get
			{
				return this._MeasureDate2;
			}
			set
			{
				if ((this._MeasureDate2 != value))
				{
					this._MeasureDate2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight2", DbType="Float")]
		public System.Nullable<double> Weight2
		{
			get
			{
				return this._Weight2;
			}
			set
			{
				if ((this._Weight2 != value))
				{
					this._Weight2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat2", DbType="Float")]
		public System.Nullable<double> Fat2
		{
			get
			{
				return this._Fat2;
			}
			set
			{
				if ((this._Fat2 != value))
				{
					this._Fat2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat2", DbType="Float")]
		public System.Nullable<double> VisFat2
		{
			get
			{
				return this._VisFat2;
			}
			set
			{
				if ((this._VisFat2 != value))
				{
					this._VisFat2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle2", DbType="Float")]
		public System.Nullable<double> Muscle2
		{
			get
			{
				return this._Muscle2;
			}
			set
			{
				if ((this._Muscle2 != value))
				{
					this._Muscle2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge2", DbType="Int")]
		public System.Nullable<int> BodyAge2
		{
			get
			{
				return this._BodyAge2;
			}
			set
			{
				if ((this._BodyAge2 != value))
				{
					this._BodyAge2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR2", DbType="Float")]
		public System.Nullable<double> BMR2
		{
			get
			{
				return this._BMR2;
			}
			set
			{
				if ((this._BMR2 != value))
				{
					this._BMR2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI2", DbType="Float")]
		public System.Nullable<double> BMI2
		{
			get
			{
				return this._BMI2;
			}
			set
			{
				if ((this._BMI2 != value))
				{
					this._BMI2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number3", DbType="Int")]
		public System.Nullable<int> Number3
		{
			get
			{
				return this._Number3;
			}
			set
			{
				if ((this._Number3 != value))
				{
					this._Number3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate3", DbType="VarChar(10)")]
		public string MeasureDate3
		{
			get
			{
				return this._MeasureDate3;
			}
			set
			{
				if ((this._MeasureDate3 != value))
				{
					this._MeasureDate3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight3", DbType="Float")]
		public System.Nullable<double> Weight3
		{
			get
			{
				return this._Weight3;
			}
			set
			{
				if ((this._Weight3 != value))
				{
					this._Weight3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat3", DbType="Float")]
		public System.Nullable<double> Fat3
		{
			get
			{
				return this._Fat3;
			}
			set
			{
				if ((this._Fat3 != value))
				{
					this._Fat3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat3", DbType="Float")]
		public System.Nullable<double> VisFat3
		{
			get
			{
				return this._VisFat3;
			}
			set
			{
				if ((this._VisFat3 != value))
				{
					this._VisFat3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle3", DbType="Float")]
		public System.Nullable<double> Muscle3
		{
			get
			{
				return this._Muscle3;
			}
			set
			{
				if ((this._Muscle3 != value))
				{
					this._Muscle3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge3", DbType="Int")]
		public System.Nullable<int> BodyAge3
		{
			get
			{
				return this._BodyAge3;
			}
			set
			{
				if ((this._BodyAge3 != value))
				{
					this._BodyAge3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR3", DbType="Float")]
		public System.Nullable<double> BMR3
		{
			get
			{
				return this._BMR3;
			}
			set
			{
				if ((this._BMR3 != value))
				{
					this._BMR3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI3", DbType="Float")]
		public System.Nullable<double> BMI3
		{
			get
			{
				return this._BMI3;
			}
			set
			{
				if ((this._BMI3 != value))
				{
					this._BMI3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number4", DbType="Int")]
		public System.Nullable<int> Number4
		{
			get
			{
				return this._Number4;
			}
			set
			{
				if ((this._Number4 != value))
				{
					this._Number4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate4", DbType="VarChar(10)")]
		public string MeasureDate4
		{
			get
			{
				return this._MeasureDate4;
			}
			set
			{
				if ((this._MeasureDate4 != value))
				{
					this._MeasureDate4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight4", DbType="Float")]
		public System.Nullable<double> Weight4
		{
			get
			{
				return this._Weight4;
			}
			set
			{
				if ((this._Weight4 != value))
				{
					this._Weight4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat4", DbType="Float")]
		public System.Nullable<double> Fat4
		{
			get
			{
				return this._Fat4;
			}
			set
			{
				if ((this._Fat4 != value))
				{
					this._Fat4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat4", DbType="Float")]
		public System.Nullable<double> VisFat4
		{
			get
			{
				return this._VisFat4;
			}
			set
			{
				if ((this._VisFat4 != value))
				{
					this._VisFat4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle4", DbType="Float")]
		public System.Nullable<double> Muscle4
		{
			get
			{
				return this._Muscle4;
			}
			set
			{
				if ((this._Muscle4 != value))
				{
					this._Muscle4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge4", DbType="Int")]
		public System.Nullable<int> BodyAge4
		{
			get
			{
				return this._BodyAge4;
			}
			set
			{
				if ((this._BodyAge4 != value))
				{
					this._BodyAge4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR4", DbType="Float")]
		public System.Nullable<double> BMR4
		{
			get
			{
				return this._BMR4;
			}
			set
			{
				if ((this._BMR4 != value))
				{
					this._BMR4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI4", DbType="Float")]
		public System.Nullable<double> BMI4
		{
			get
			{
				return this._BMI4;
			}
			set
			{
				if ((this._BMI4 != value))
				{
					this._BMI4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number5", DbType="Int")]
		public System.Nullable<int> Number5
		{
			get
			{
				return this._Number5;
			}
			set
			{
				if ((this._Number5 != value))
				{
					this._Number5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate5", DbType="VarChar(10)")]
		public string MeasureDate5
		{
			get
			{
				return this._MeasureDate5;
			}
			set
			{
				if ((this._MeasureDate5 != value))
				{
					this._MeasureDate5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight5", DbType="Float")]
		public System.Nullable<double> Weight5
		{
			get
			{
				return this._Weight5;
			}
			set
			{
				if ((this._Weight5 != value))
				{
					this._Weight5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat5", DbType="Float")]
		public System.Nullable<double> Fat5
		{
			get
			{
				return this._Fat5;
			}
			set
			{
				if ((this._Fat5 != value))
				{
					this._Fat5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat5", DbType="Float")]
		public System.Nullable<double> VisFat5
		{
			get
			{
				return this._VisFat5;
			}
			set
			{
				if ((this._VisFat5 != value))
				{
					this._VisFat5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle5", DbType="Float")]
		public System.Nullable<double> Muscle5
		{
			get
			{
				return this._Muscle5;
			}
			set
			{
				if ((this._Muscle5 != value))
				{
					this._Muscle5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge5", DbType="Int")]
		public System.Nullable<int> BodyAge5
		{
			get
			{
				return this._BodyAge5;
			}
			set
			{
				if ((this._BodyAge5 != value))
				{
					this._BodyAge5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR5", DbType="Float")]
		public System.Nullable<double> BMR5
		{
			get
			{
				return this._BMR5;
			}
			set
			{
				if ((this._BMR5 != value))
				{
					this._BMR5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI5", DbType="Float")]
		public System.Nullable<double> BMI5
		{
			get
			{
				return this._BMI5;
			}
			set
			{
				if ((this._BMI5 != value))
				{
					this._BMI5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat", DbType="Float")]
		public System.Nullable<double> Fat
		{
			get
			{
				return this._Fat;
			}
			set
			{
				if ((this._Fat != value))
				{
					this._Fat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat", DbType="Float")]
		public System.Nullable<double> VisFat
		{
			get
			{
				return this._VisFat;
			}
			set
			{
				if ((this._VisFat != value))
				{
					this._VisFat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle", DbType="Float")]
		public System.Nullable<double> Muscle
		{
			get
			{
				return this._Muscle;
			}
			set
			{
				if ((this._Muscle != value))
				{
					this._Muscle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge", DbType="Int")]
		public System.Nullable<int> BodyAge
		{
			get
			{
				return this._BodyAge;
			}
			set
			{
				if ((this._BodyAge != value))
				{
					this._BodyAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR", DbType="Float")]
		public System.Nullable<double> BMR
		{
			get
			{
				return this._BMR;
			}
			set
			{
				if ((this._BMR != value))
				{
					this._BMR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Float")]
		public System.Nullable<double> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this._BMI = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_ChallengeResult_Report")]
	public partial class V_ChallengeResult_Report
	{
		
		private string _UserNo;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _NickName;
		
		private string _Telephone;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<double> _Height;
		
		private string _Gender;
		
		private string _Invitor;
		
		private string _LineID;
		
		private System.Nullable<int> _Page;
		
		private System.Nullable<int> _Number1;
		
		private string _MeasureDate1;
		
		private System.Nullable<double> _Weight1;
		
		private System.Nullable<double> _Fat1;
		
		private System.Nullable<double> _VisFat1;
		
		private System.Nullable<double> _Muscle1;
		
		private System.Nullable<int> _BodyAge1;
		
		private System.Nullable<double> _BMR1;
		
		private System.Nullable<double> _BMI1;
		
		private System.Nullable<int> _Number2;
		
		private string _MeasureDate2;
		
		private System.Nullable<double> _Weight2;
		
		private System.Nullable<double> _Fat2;
		
		private System.Nullable<double> _VisFat2;
		
		private System.Nullable<double> _Muscle2;
		
		private System.Nullable<int> _BodyAge2;
		
		private System.Nullable<double> _BMR2;
		
		private System.Nullable<double> _BMI2;
		
		private System.Nullable<int> _Number3;
		
		private string _MeasureDate3;
		
		private System.Nullable<double> _Weight3;
		
		private System.Nullable<double> _Fat3;
		
		private System.Nullable<double> _VisFat3;
		
		private System.Nullable<double> _Muscle3;
		
		private System.Nullable<int> _BodyAge3;
		
		private System.Nullable<double> _BMR3;
		
		private System.Nullable<double> _BMI3;
		
		private System.Nullable<int> _Number4;
		
		private string _MeasureDate4;
		
		private System.Nullable<double> _Weight4;
		
		private System.Nullable<double> _Fat4;
		
		private System.Nullable<double> _VisFat4;
		
		private System.Nullable<double> _Muscle4;
		
		private System.Nullable<int> _BodyAge4;
		
		private System.Nullable<double> _BMR4;
		
		private System.Nullable<double> _BMI4;
		
		private System.Nullable<int> _Number5;
		
		private string _MeasureDate5;
		
		private System.Nullable<double> _Weight5;
		
		private System.Nullable<double> _Fat5;
		
		private System.Nullable<double> _VisFat5;
		
		private System.Nullable<double> _Muscle5;
		
		private System.Nullable<int> _BodyAge5;
		
		private System.Nullable<double> _BMR5;
		
		private System.Nullable<double> _BMI5;
		
		private System.Nullable<double> _Fat;
		
		private System.Nullable<double> _VisFat;
		
		private System.Nullable<double> _Muscle;
		
		private System.Nullable<int> _BodyAge;
		
		private System.Nullable<double> _BMR;
		
		private System.Nullable<double> _BMI;
		
		public V_ChallengeResult_Report()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UserNo
		{
			get
			{
				return this._UserNo;
			}
			set
			{
				if ((this._UserNo != value))
				{
					this._UserNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName", DbType="VarChar(50)")]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this._NickName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Float")]
		public System.Nullable<double> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this._Height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(1)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invitor", DbType="VarChar(50)")]
		public string Invitor
		{
			get
			{
				return this._Invitor;
			}
			set
			{
				if ((this._Invitor != value))
				{
					this._Invitor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineID", DbType="VarChar(50)")]
		public string LineID
		{
			get
			{
				return this._LineID;
			}
			set
			{
				if ((this._LineID != value))
				{
					this._LineID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Page", DbType="Int")]
		public System.Nullable<int> Page
		{
			get
			{
				return this._Page;
			}
			set
			{
				if ((this._Page != value))
				{
					this._Page = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number1", DbType="Int")]
		public System.Nullable<int> Number1
		{
			get
			{
				return this._Number1;
			}
			set
			{
				if ((this._Number1 != value))
				{
					this._Number1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate1", DbType="VarChar(10)")]
		public string MeasureDate1
		{
			get
			{
				return this._MeasureDate1;
			}
			set
			{
				if ((this._MeasureDate1 != value))
				{
					this._MeasureDate1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight1", DbType="Float")]
		public System.Nullable<double> Weight1
		{
			get
			{
				return this._Weight1;
			}
			set
			{
				if ((this._Weight1 != value))
				{
					this._Weight1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat1", DbType="Float")]
		public System.Nullable<double> Fat1
		{
			get
			{
				return this._Fat1;
			}
			set
			{
				if ((this._Fat1 != value))
				{
					this._Fat1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat1", DbType="Float")]
		public System.Nullable<double> VisFat1
		{
			get
			{
				return this._VisFat1;
			}
			set
			{
				if ((this._VisFat1 != value))
				{
					this._VisFat1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle1", DbType="Float")]
		public System.Nullable<double> Muscle1
		{
			get
			{
				return this._Muscle1;
			}
			set
			{
				if ((this._Muscle1 != value))
				{
					this._Muscle1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge1", DbType="Int")]
		public System.Nullable<int> BodyAge1
		{
			get
			{
				return this._BodyAge1;
			}
			set
			{
				if ((this._BodyAge1 != value))
				{
					this._BodyAge1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR1", DbType="Float")]
		public System.Nullable<double> BMR1
		{
			get
			{
				return this._BMR1;
			}
			set
			{
				if ((this._BMR1 != value))
				{
					this._BMR1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI1", DbType="Float")]
		public System.Nullable<double> BMI1
		{
			get
			{
				return this._BMI1;
			}
			set
			{
				if ((this._BMI1 != value))
				{
					this._BMI1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number2", DbType="Int")]
		public System.Nullable<int> Number2
		{
			get
			{
				return this._Number2;
			}
			set
			{
				if ((this._Number2 != value))
				{
					this._Number2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate2", DbType="VarChar(10)")]
		public string MeasureDate2
		{
			get
			{
				return this._MeasureDate2;
			}
			set
			{
				if ((this._MeasureDate2 != value))
				{
					this._MeasureDate2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight2", DbType="Float")]
		public System.Nullable<double> Weight2
		{
			get
			{
				return this._Weight2;
			}
			set
			{
				if ((this._Weight2 != value))
				{
					this._Weight2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat2", DbType="Float")]
		public System.Nullable<double> Fat2
		{
			get
			{
				return this._Fat2;
			}
			set
			{
				if ((this._Fat2 != value))
				{
					this._Fat2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat2", DbType="Float")]
		public System.Nullable<double> VisFat2
		{
			get
			{
				return this._VisFat2;
			}
			set
			{
				if ((this._VisFat2 != value))
				{
					this._VisFat2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle2", DbType="Float")]
		public System.Nullable<double> Muscle2
		{
			get
			{
				return this._Muscle2;
			}
			set
			{
				if ((this._Muscle2 != value))
				{
					this._Muscle2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge2", DbType="Int")]
		public System.Nullable<int> BodyAge2
		{
			get
			{
				return this._BodyAge2;
			}
			set
			{
				if ((this._BodyAge2 != value))
				{
					this._BodyAge2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR2", DbType="Float")]
		public System.Nullable<double> BMR2
		{
			get
			{
				return this._BMR2;
			}
			set
			{
				if ((this._BMR2 != value))
				{
					this._BMR2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI2", DbType="Float")]
		public System.Nullable<double> BMI2
		{
			get
			{
				return this._BMI2;
			}
			set
			{
				if ((this._BMI2 != value))
				{
					this._BMI2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number3", DbType="Int")]
		public System.Nullable<int> Number3
		{
			get
			{
				return this._Number3;
			}
			set
			{
				if ((this._Number3 != value))
				{
					this._Number3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate3", DbType="VarChar(10)")]
		public string MeasureDate3
		{
			get
			{
				return this._MeasureDate3;
			}
			set
			{
				if ((this._MeasureDate3 != value))
				{
					this._MeasureDate3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight3", DbType="Float")]
		public System.Nullable<double> Weight3
		{
			get
			{
				return this._Weight3;
			}
			set
			{
				if ((this._Weight3 != value))
				{
					this._Weight3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat3", DbType="Float")]
		public System.Nullable<double> Fat3
		{
			get
			{
				return this._Fat3;
			}
			set
			{
				if ((this._Fat3 != value))
				{
					this._Fat3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat3", DbType="Float")]
		public System.Nullable<double> VisFat3
		{
			get
			{
				return this._VisFat3;
			}
			set
			{
				if ((this._VisFat3 != value))
				{
					this._VisFat3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle3", DbType="Float")]
		public System.Nullable<double> Muscle3
		{
			get
			{
				return this._Muscle3;
			}
			set
			{
				if ((this._Muscle3 != value))
				{
					this._Muscle3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge3", DbType="Int")]
		public System.Nullable<int> BodyAge3
		{
			get
			{
				return this._BodyAge3;
			}
			set
			{
				if ((this._BodyAge3 != value))
				{
					this._BodyAge3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR3", DbType="Float")]
		public System.Nullable<double> BMR3
		{
			get
			{
				return this._BMR3;
			}
			set
			{
				if ((this._BMR3 != value))
				{
					this._BMR3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI3", DbType="Float")]
		public System.Nullable<double> BMI3
		{
			get
			{
				return this._BMI3;
			}
			set
			{
				if ((this._BMI3 != value))
				{
					this._BMI3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number4", DbType="Int")]
		public System.Nullable<int> Number4
		{
			get
			{
				return this._Number4;
			}
			set
			{
				if ((this._Number4 != value))
				{
					this._Number4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate4", DbType="VarChar(10)")]
		public string MeasureDate4
		{
			get
			{
				return this._MeasureDate4;
			}
			set
			{
				if ((this._MeasureDate4 != value))
				{
					this._MeasureDate4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight4", DbType="Float")]
		public System.Nullable<double> Weight4
		{
			get
			{
				return this._Weight4;
			}
			set
			{
				if ((this._Weight4 != value))
				{
					this._Weight4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat4", DbType="Float")]
		public System.Nullable<double> Fat4
		{
			get
			{
				return this._Fat4;
			}
			set
			{
				if ((this._Fat4 != value))
				{
					this._Fat4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat4", DbType="Float")]
		public System.Nullable<double> VisFat4
		{
			get
			{
				return this._VisFat4;
			}
			set
			{
				if ((this._VisFat4 != value))
				{
					this._VisFat4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle4", DbType="Float")]
		public System.Nullable<double> Muscle4
		{
			get
			{
				return this._Muscle4;
			}
			set
			{
				if ((this._Muscle4 != value))
				{
					this._Muscle4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge4", DbType="Int")]
		public System.Nullable<int> BodyAge4
		{
			get
			{
				return this._BodyAge4;
			}
			set
			{
				if ((this._BodyAge4 != value))
				{
					this._BodyAge4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR4", DbType="Float")]
		public System.Nullable<double> BMR4
		{
			get
			{
				return this._BMR4;
			}
			set
			{
				if ((this._BMR4 != value))
				{
					this._BMR4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI4", DbType="Float")]
		public System.Nullable<double> BMI4
		{
			get
			{
				return this._BMI4;
			}
			set
			{
				if ((this._BMI4 != value))
				{
					this._BMI4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number5", DbType="Int")]
		public System.Nullable<int> Number5
		{
			get
			{
				return this._Number5;
			}
			set
			{
				if ((this._Number5 != value))
				{
					this._Number5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureDate5", DbType="VarChar(10)")]
		public string MeasureDate5
		{
			get
			{
				return this._MeasureDate5;
			}
			set
			{
				if ((this._MeasureDate5 != value))
				{
					this._MeasureDate5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight5", DbType="Float")]
		public System.Nullable<double> Weight5
		{
			get
			{
				return this._Weight5;
			}
			set
			{
				if ((this._Weight5 != value))
				{
					this._Weight5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat5", DbType="Float")]
		public System.Nullable<double> Fat5
		{
			get
			{
				return this._Fat5;
			}
			set
			{
				if ((this._Fat5 != value))
				{
					this._Fat5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat5", DbType="Float")]
		public System.Nullable<double> VisFat5
		{
			get
			{
				return this._VisFat5;
			}
			set
			{
				if ((this._VisFat5 != value))
				{
					this._VisFat5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle5", DbType="Float")]
		public System.Nullable<double> Muscle5
		{
			get
			{
				return this._Muscle5;
			}
			set
			{
				if ((this._Muscle5 != value))
				{
					this._Muscle5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge5", DbType="Int")]
		public System.Nullable<int> BodyAge5
		{
			get
			{
				return this._BodyAge5;
			}
			set
			{
				if ((this._BodyAge5 != value))
				{
					this._BodyAge5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR5", DbType="Float")]
		public System.Nullable<double> BMR5
		{
			get
			{
				return this._BMR5;
			}
			set
			{
				if ((this._BMR5 != value))
				{
					this._BMR5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI5", DbType="Float")]
		public System.Nullable<double> BMI5
		{
			get
			{
				return this._BMI5;
			}
			set
			{
				if ((this._BMI5 != value))
				{
					this._BMI5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fat", DbType="Float")]
		public System.Nullable<double> Fat
		{
			get
			{
				return this._Fat;
			}
			set
			{
				if ((this._Fat != value))
				{
					this._Fat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisFat", DbType="Float")]
		public System.Nullable<double> VisFat
		{
			get
			{
				return this._VisFat;
			}
			set
			{
				if ((this._VisFat != value))
				{
					this._VisFat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muscle", DbType="Float")]
		public System.Nullable<double> Muscle
		{
			get
			{
				return this._Muscle;
			}
			set
			{
				if ((this._Muscle != value))
				{
					this._Muscle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyAge", DbType="Int")]
		public System.Nullable<int> BodyAge
		{
			get
			{
				return this._BodyAge;
			}
			set
			{
				if ((this._BodyAge != value))
				{
					this._BodyAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR", DbType="Float")]
		public System.Nullable<double> BMR
		{
			get
			{
				return this._BMR;
			}
			set
			{
				if ((this._BMR != value))
				{
					this._BMR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Float")]
		public System.Nullable<double> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this._BMI = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_ChallengeResult_PageNo")]
	public partial class Page : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<long> _RecNo;
		
		private string _UserNo;
		
		private System.Nullable<int> _PageNo;
		
		private EntityRef<Challenger> _Challenger;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecNoChanging(System.Nullable<long> value);
    partial void OnRecNoChanged();
    partial void OnUserNoChanging(string value);
    partial void OnUserNoChanged();
    partial void OnPageNoChanging(System.Nullable<int> value);
    partial void OnPageNoChanged();
    #endregion
		
		public Page()
		{
			this._Challenger = default(EntityRef<Challenger>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecNo", DbType="BigInt", IsPrimaryKey=true)]
		public System.Nullable<long> RecNo
		{
			get
			{
				return this._RecNo;
			}
			set
			{
				if ((this._RecNo != value))
				{
					this.OnRecNoChanging(value);
					this.SendPropertyChanging();
					this._RecNo = value;
					this.SendPropertyChanged("RecNo");
					this.OnRecNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UserNo
		{
			get
			{
				return this._UserNo;
			}
			set
			{
				if ((this._UserNo != value))
				{
					if (this._Challenger.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserNoChanging(value);
					this.SendPropertyChanging();
					this._UserNo = value;
					this.SendPropertyChanged("UserNo");
					this.OnUserNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageNo", DbType="Int")]
		public System.Nullable<int> PageNo
		{
			get
			{
				return this._PageNo;
			}
			set
			{
				if ((this._PageNo != value))
				{
					this.OnPageNoChanging(value);
					this.SendPropertyChanging();
					this._PageNo = value;
					this.SendPropertyChanged("PageNo");
					this.OnPageNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Challenger_Page", Storage="_Challenger", ThisKey="UserNo", OtherKey="UserNo", IsForeignKey=true)]
		public Challenger Challenger
		{
			get
			{
				return this._Challenger.Entity;
			}
			set
			{
				Challenger previousValue = this._Challenger.Entity;
				if (((previousValue != value) 
							|| (this._Challenger.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Challenger.Entity = null;
						previousValue.Pages.Remove(this);
					}
					this._Challenger.Entity = value;
					if ((value != null))
					{
						value.Pages.Add(this);
						this._UserNo = value.UserNo;
					}
					else
					{
						this._UserNo = default(string);
					}
					this.SendPropertyChanged("Challenger");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserNo;
		
		private string _Password;
		
		private string _FullName;
		
		private char _UserType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNoChanging(string value);
    partial void OnUserNoChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnUserTypeChanging(char value);
    partial void OnUserTypeChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserNo
		{
			get
			{
				return this._UserNo;
			}
			set
			{
				if ((this._UserNo != value))
				{
					this.OnUserNoChanging(value);
					this.SendPropertyChanging();
					this._UserNo = value;
					this.SendPropertyChanged("UserNo");
					this.OnUserNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="Char(1) NOT NULL")]
		public char UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
